### ISSUE TITLE
Crash when there's no bluetooth adapter available

### ISSUE THREAD

**Issue by SvenDub** [SvenDub/Dashboard#2]
Stack trace:

```
08-08 12:31:33.028    6013-6013/nl.svendubbeld.car E/BluetoothAdapter﹕ Bluetooth binder is null
08-08 12:31:33.028    6013-6013/nl.svendubbeld.car D/AndroidRuntime﹕ Shutting down VM
08-08 12:31:33.028    6013-6013/nl.svendubbeld.car E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: nl.svendubbeld.car, PID: 6013
    java.lang.RuntimeException: Unable to resume activity {nl.svendubbeld.car/nl.svendubbeld.car.activity.ObdActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.bluetooth.BluetoothAdapter.isEnabled()' on a null object reference
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2989)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3020)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2395)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5257)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.bluetooth.BluetoothAdapter.isEnabled()' on a null object reference
            at nl.svendubbeld.car.activity.ObdActivity.onResume(ObdActivity.java:198)
            at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1257)
            at android.app.Activity.performResume(Activity.java:6076)
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2978)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3020)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2395)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5257)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by SvenDub** [comment]
No longer relevant after rewrite.
